データをDBに書き込みました
playground-live/alfred-github-workflow pull request #4
Opened 2017-11-23 06:51 UTC by akias

2017-11-24 01:14 UTC, ikepon commented on github.rb
> +    results
この `results` 必要でしたか？なしでも動くような...

2017-11-24 01:18 UTC, ikepon commented on github/cache/load.rb
> +        requests = db.execute('select *from repos')
細かいんですが、 `select * from repos` ってスペースを入れると読みやすくなると思いました。

2017-11-24 01:28 UTC, ikepon commented on github/cache/load.rb
> +        requests = db.execute('select *from repos')
`db.execute('select * from repos')` って何が返ってくるんですか？

何となくSQLを実行した結果が返ってくるような気がしたので、それに合わせた名前のほうがいいのかなと思いました。

ついでに、この `requests` への代入って必要でした？
```
        requests = db.execute("select *from issues where status = 'open' order by id desc")
        requests
```

この一行 ⬇️ だけでいいような気がしました。(同じ結果にならなかったらごめんなさい 🙇 )
```
db.execute("select *from issues where status = 'open' order by id desc")
```

2017-11-24 06:56 UTC, wnsll commented on github.rb
>      end
個人の意見ですが、同じ引数複数の場合、共通変数として使ったほうがいいと思います。
たとえば：db

2017-11-24 08:04 UTC, ebkn requested changes

2017-11-24 08:04 UTC, ebkn12 commented on github.rb
>  require './xml_builder'
相対パスで書くなら、下と揃えて`require_relative`で記述した方が良いと思う

2017-11-24 08:04 UTC, ebkn12 commented on github.rb
>  # method with github
このコメントはいらない気がする

2017-11-24 08:04 UTC, ebkn12 commented on github/cache/update.rb
> +          );
SQL文は大文字で書くか小文字で書くか統一した方がわかりやすいと思う

2017-11-24 08:04 UTC, ebkn12 commented on github/cache/update.rb
> +        SQL
SQL文をネストさせるか統一させた方がいいと思う
```
sql = <<-SQL
  create table
  ...
  );
SQL
```

2017-11-24 08:29 UTC, akias commented on github.rb
> +    results
確かにそうですね。ありがとうございます！

2017-11-24 08:49 UTC, akias commented on github/cache/load.rb
> +        requests = db.execute('select *from repos')
了解です。
`db.execute("select *from issues where status = 'open' order by id desc")`で修正します。

2017-11-24 09:25 UTC, akias commented on github.rb
>  require './xml_builder'
修正しました

2017-11-24 09:29 UTC, akias commented on github.rb
>  # method with github
了解

2017-11-24 09:30 UTC, akias commented on github/cache/update.rb
> +          );
ok

2017-11-24 09:30 UTC, akias commented on github/cache/update.rb
> +        SQL
修正しました

2017-11-24 09:46 UTC, akias commented on github.rb
>      end
ありがとうございます！修正しました

2019-04-03 01:22 UTC, akias commented
結構昔のものなので、一旦クローズする。

2019-04-03 01:22 UTC, closed without merging